# Auto-generated by /home/william/SerranonOS/UEFI/vUDK2017/BaseTools/BuildEnv
if [ -z "$WORKSPACE" ]
then
  export WORKSPACE=/home/william/SerranonOS/UEFI/vUDK2017
fi
if [ -z "$EDK_TOOLS_PATH" ]
then
  export EDK_TOOLS_PATH=/home/william/SerranonOS/UEFI/vUDK2017/BaseTools
fi
if [ -e /home/william/SerranonOS/UEFI/vUDK2017/BaseTools/Bin/Linux-x86_64 ]
then
  if [ ${PATH//home/william/SerranonOS/UEFI/vUDK2017/BaseTools/Bin/Linux-x86_64/} == $PATH ]
  then
    export PATH=/home/william/SerranonOS/UEFI/vUDK2017/BaseTools/Bin/Linux-x86_64:$PATH
  fi
fi
