# Auto-generated by /mnt/c/SerranonOS/UEFI/vUDK2017/BaseTools/BuildEnv
if [ -z "$WORKSPACE" ]
then
  export WORKSPACE=/mnt/c/SerranonOS/UEFI/vUDK2017
fi
if [ -z "$EDK_TOOLS_PATH" ]
then
  export EDK_TOOLS_PATH=/mnt/c/SerranonOS/UEFI/vUDK2017/BaseTools
fi
if [ -e /mnt/c/SerranonOS/UEFI/vUDK2017/BaseTools/Bin/Linux-x86_64 ]
then
  if [ ${PATH//mnt/c/SerranonOS/UEFI/vUDK2017/BaseTools/Bin/Linux-x86_64/} == $PATH ]
  then
    export PATH=/mnt/c/SerranonOS/UEFI/vUDK2017/BaseTools/Bin/Linux-x86_64:$PATH
  fi
fi
